services:
  user-service-db:
    image: docker.io/library/postgres:latest
    container_name: user-service-db
    hostname: user-service-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - user-service
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

networks:
  user-service:
    driver: bridge
volumes:
  data:
